#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Wearesho\Delivery\TurboSms\Tests\Console;
use Symfony\Component\Console\Application;
use Dotenv\Dotenv;

$dotenv = Dotenv::createImmutable(__DIR__);
$dotenv->safeLoad();
$dotenv->required(['TURBOSMS_LOGIN', 'TURBOSMS_PASSWORD', 'TURBOSMS_SENDER']);

$application = new Application();
$application->addCommands([
    new Console\Command(),
    new Console\MessageCommand(),
]);
$application->run();
